name: CI

on: [pull_request, workflow_dispatch]

jobs:
  phpstan:
    strategy:
      matrix:
        php-version:
          - 8.1
          - 8.2
    uses: BrandEmbassy/github-actions/.github/workflows/php-phpstan.yml@master
    with:
      PHP_VERSION: ${{ matrix.php-version }}

  ecs:
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - 8.1
          - 8.2
    uses: BrandEmbassy/github-actions/.github/workflows/php-ecs.yml@master
    with:
      PHP_VERSION: ${{ matrix.php-version }}

  rector:
    uses: BrandEmbassy/github-actions/.github/workflows/php-rector.yml@master
    with:
      PHP_VERSION: '8.1'
      RECTOR_CACHE_PATH: './var/rector'

  phpunit:
    strategy:
      matrix:
        composer-arg:
          - "install"
          - "update --prefer-lowest"
        php-version:
          - 8.1
          - 8.2
        exclude:
          - composer-arg: install
            php-version: 8.1
    uses: BrandEmbassy/github-actions/.github/workflows/php-phpunit.yml@master
    with:
      COMPOSER_ARG: ${{ matrix.composer-arg }}
      PHP_VERSION: ${{ matrix.php-version }}
      COPY_CONFIGURATION_FILES: tests/config.neon.example:tests/config.neon
      SERVICES: mysql

  phpunit-with-sonar-qube:
    uses: BrandEmbassy/github-actions/.github/workflows/php-phpunit-with-sonar-qube.yml@master
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    with:
      COPY_CONFIGURATION_FILES: tests/config.neon.example:tests/config.neon
      SERVICES: mysql
